import fs from 'fs'
import matter from 'gray-matter'
import Link from 'next/link'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

type Blog = {
  title: string
  date: string
  slug: string
}

export default function Home({ blogs }: { blogs: Blog[] }) {
  if (!blogs.length) {
    return <></>
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Mikas Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Hello Blog</h1>
        <ul>
          {blogs.map((blog) => (
            <li key={blog.slug}>
              <Link href={`/test-blog/${blog.slug}`}>
                {blog.date}: {blog.title}
              </Link>
            </li>
          ))}
        </ul>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const files = fs.readdirSync('./src/test-blogs')
  const blogs = files.map((file) => {
    const fileName = fs.readFileSync(`./src/test-blogs/${file}`)
    const matterData = matter(fileName)

    return {
      ...matterData.data,
      slug: file.slice(0, file.indexOf('.')),
    }
  })

  return {
    props: {
      blogs,
    },
  }
}
